const supabaseUrl = 'https://jefezrjkvopvyjzqfatd.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZmV6cmprdm9wdnlqenFmYXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTQ0MzgsImV4cCI6MjA3MTY5MDQzOH0.cSRBoS3rMZeO1SOQjGWgzTDtYEJZ4FA_BMTMoB5oXjU';
